version: 0.0
os: linux

files:
  - source: /
destination: /var/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
  - location: bin/messengerserver/Server.class
  timeout: 300
  runas: ec2-user