version: 0.0
os: linux

files:
  - source: /
    destination: /var/server

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: bin/messengerserver/Server.class
      timeout: 300
      runas: root